#!/bin/bash
# UTILITIES BASICAS PARA EL TERMINAL
  apt-get update
  apt-get upgrade -y

# Utilitarios varios:
  sudo apt install curl wget zip unzip

# nala (front-end para apt)
  curl https://gitlab.com/volian/volian-archive/-/raw/main/install-nala.sh | bash
  
# Confirmador de reseteos y apagados remotos ( https://adrianroselli.com/wp-content/uploads/2024/02/switch-with-molly-guard.jpg ):
  sudo nala install molly-guard

# Navegador de archivos:
  sudo nala install ranger

# Fonts:
  # Preparar un directorio ordenado para los fonts monoespaciados extra:
    sudo mkdir -p /usr/share/fonts/Extra/Monoesp
  # Victor Mono:
    wget https://rubjo.github.io/victor-mono/VictorMonoAll.zip -O ~/Downloads/VictorMonoAll.zip
    sudo unzip ~/Downloads/VictorMonoAll.zip -d /usr/share/fonts/Extra/Monoesp/VictorMono
    rm ~/Downloads/VictorMonoAll.zip

    

# Multi terminal moderno, verstil y multiplataforma ( https://tabby.sh https://github.com/Eugeny/tabby ):
  wget https://github.com/Eugeny/tabby/releases/download/v1.0.225/tabby-1.0.225-linux-x64.deb -O ~/Downloads/Tabby.deb
  sudo apt install ~/Downloads/Tabby.deb

# Utilities de audio:
#  paplay - Playback a WAV file via a PulseAudio sink.
#  pacat - Cat raw audio data to a PulseAudio sink.
#  parec - Cat raw audio data from a PulseAudio source.
#  pacmd - Connect to PulseAudio's built-in command line control interface.
#  pactl - Send a control command to a PulseAudio server.
#  padsp - /dev/dsp wrapper to transparently support OSS applications.
#  pax11publish - Store/retrieve PulseAudio default server/sink/source settings in the X11 root window.
  sudo nala install pulseaudio-utils

# fzf (FuZzy files, buscador de archivos)
  sudo nala install -y fzf

# dust (analizador de ocupación de disco, mas informativo que du)
# Requiere rust, no lo instalé por evitar bloat

# bat (cat, pero con resaltado de sintaxis) (despues hay que usar batcat, agregado a los aliases)
  sudo nala install -y bat

# tldr (Man pages resumido)
  sudo nala install -y tldr

# FORMATEADORES DE INFORMACION DEL EQUIPO:
# Informacion general:
  wget https://github.com/fastfetch-cli/fastfetch/releases/download/2.21.3/fastfetch-linux-amd64.deb
  sudo apt install ~/fastfetch-linux-amd64.deb
  rm ~/fastfetch-linux-amd64.deb
# Información del CPU:
  sudo apt install build-essential
  git clone https://github.com/Dr-Noob/cpufetch
  cd cpufetch
  make
  sudo mv ~/cpufetch/cpufetch /usr/bin/
# Determinacion de rendimiento:  

# Utilities Android:
  sudo nala install android-sdk-platform-tools-common
  sudo nala install adb fastboot
  sudo cp /lib/udev/rules.d/51-android.rules /etc/udev/rules.d/
    #  wget --output-document=ADB.zip https://dl.google.com/android/repository/platform-tools-latest-linux.zip
    #  unzip ADB.zip
    #  rm ADB.zip
    #  sudo mv ~/platform-tools /usr/bin/android-tools
    ## Agregar al path común en /Discos/Local/bashStd/.bashrc
    #    export PATH=$PATH:/usr/bin/android-tools
