#!/bin/bash
# UTILITIES BASICAS PARA EL TERMINAL
  apt-get update
  apt-get upgrade -y

# Utilitarios varios:
  sudo apt install curl wget zip unzip

# nala (front-end para apt)
  curl https://gitlab.com/volian/volian-archive/-/raw/main/install-nala.sh | bash
  
