#!/bin/bash
# UTILITIES BASICAS PARA EL TERMINAL

# Instalar los comandos para descarga web
  sudo apt install curl wget

# nala (front-end para apt)
  curl https://gitlab.com/volian/volian-archive/-/raw/main/install-nala.sh | bash
  
  sudo nala install zip unzip
