#!/bin/bash
me="$(cat /sys/class/dmi/id/board_vendor) $(cat /sys/class/dmi/id/board_name)"

me=$me$( grep -E "model name" /proc/cpuinfo | cut -d ':' -f 2 | wc -l )"x"
me=$me$( grep -E "model name" /proc/cpuinfo | cut -d ':' -f 2 | head -1 )", "

me=$me$( awk  '/MemAvailable/ {printf( "%.2f\n", $2 / 1048576 )}' /proc/meminfo )
me=$me"/"$( awk '/MemTotal/ {printf( "%.2f\n", $2 / 1048526 )}' /proc/meminfo )
me=$me"GBRAM"
echo " "$me

Cfg=$(grep -E '^NAME' /etc/os-release | cut -d '=' -f 2)
Cfg=$Cfg" "$(grep -E 'VERSION_FULL=' /etc/os-release | cut -d '=' -f 2)
Cfg=$Cfg" "$(grep -E 'VERSION_CODENAME=' /etc/os-release | cut -d '=' -f 2)
Cfg=$(echo $Cfg | sed 's/\"//g')
echo " ejecutando" $Cfg "desde "$(uptime -s)

