#!/bin/bash

# Anunciar el IP

# Buscar el IP de la ruta por defecto, seguramente es en
#  el mismo segmento de red que el IP principal de este host:
  GW=$(ip route | grep default | cut -d ' ' -f 3)

# Cortar el último byte para obtener el segmento de red:
  IP=${GW%.*}
# Listar todos los IPs pero devolver solo el que está en este segmento
  IP=$(ip a | grep $IP)
# Eliminar los varios espacios al inicio ...
  IP=$(echo $IP | sed -e 's/^[[:space:]]*//')
# ... para no confundir al 'cut' y que devuelva el campo correcto
  IP=$(echo $IP | cut -d ' ' -f 2)

## Resolver un dominio y devolver solo el server:
#  NS=$(nslookup google.com | grep Server)
## Tomar sólo el segundo campo:
#  NS=$(echo $NS | cut -d ' ' -f 2)

# Parsear el nameserver:
  NS=$(cat /etc/resolv.conf | grep -im 1 '^nameserver' | cut -d ' ' -f2)

# Informar acerca de la red:
  echo -e " IP=$IP   NS=$NS   GW=$GW"


