#!/bin/bash
# UTILITIES EXTRA PARA EL TERMINAL

# Evitador de reseteos y apagados equivocados ( https://adrianroselli.com/wp-content/uploads/2024/02/switch-with-molly-guard.jpg ):
  sudo nala install molly-guard
# sudo reboot
# W: molly-guard: SSH session detected!
#  Please type in hostname of the machine to reboot: ^C
#  Good thing I asked; I won't reboot EsteEquipo ...

# Utilities de audio:
#  paplay - Playback a WAV file via a PulseAudio sink.
#  pacat - Cat raw audio data to a PulseAudio sink.
#  parec - Cat raw audio data from a PulseAudio source.
#  pacmd - Connect to PulseAudio's built-in command line control interface.
#  pactl - Send a control command to a PulseAudio server.
#  padsp - /dev/dsp wrapper to transparently support OSS applications.
#  pax11publish - Store/retrieve PulseAudio default server/sink/source settings in the X11 root window.
  sudo nala install pulseaudio-utils

# fzf (FuZzy files, buscador de archivos)
  sudo nala install -y fzf

# atuin (History mas versatil)
# NUNCA PUDE 
  curl --proto '=https' --tlsv1.2 -LsSf https://setup.atuin.sh | bash 

# dust (analizador de ocupación de disco, mas informatica que du)
# Requiere rust, no lo instalé por evitar bloat

# bat (cat, pero con resaltado de sintaxis) (despues hay que usar batcat, agregado a los aliases)
  sudo nala install -y bat

# tldr (Man pages resumido)
  sudo nala install -y tldr

# eza (Sustituto mejorado de ls)
  sudo mkdir -p /etc/apt/keyrings
  wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
  echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list
  sudo chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list
  sudo apt update
  sudo nala install -y eza
# https://github.com/eza-community/eza/blob/main/man/eza_colors.5.md

# FORMATEADORES DE INFORMACION DEL EQUIPO:
# Informacion general:
  wget https://github.com/fastfetch-cli/fastfetch/releases/download/2.21.3/fastfetch-linux-amd64.deb
  sudo apt install ~/fastfetch-linux-amd64.deb
  rm ~/fastfetch-linux-amd64.deb
# Información del CPU:
  sudo apt install build-essential
  git clone https://github.com/Dr-Noob/cpufetch
  cd cpufetch
  make
  sudo mv ~/cpufetch/cpufetch /usr/bin/
# Determinacion de rendimiento:  

# Utilities Android:
  sudo nala install -y android-sdk-platform-tools-common
  sudo nala install android-tools-adb
  sudo cp /lib/udev/rules.d/51-android.rules /etc/udev/rules.d/
    #  wget --output-document=ADB.zip https://dl.google.com/android/repository/platform-tools-latest-linux.zip
    #  unzip ADB.zip
    #  rm ADB.zip
    #  sudo mv ~/platform-tools /usr/bin/android-tools
    ## Agregar al path común en /Discos/Local/bashStd/.bashrc
    #    export PATH=$PATH:/usr/bin/android-tools
